name: Type Report
on:
  - pull_request

permissions:
  pull-requests: write

jobs:
  type_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Type Report
        run: npm run type:report > type-coverage.txt

      - name: Create or Update PR Comment 💬
        uses: actions/github-script@main
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const cmts = await github.rest.issues.listComments({ issue_number, owner, repo });

            const comment = cmts.data.find(cmt => cmt.user.login === 'github-actions[bot]');

            const fs = require('fs');
            const path = './type-coverage.txt';
            const body = fs.readFileSync(path, 'utf8');
            comment
                ? github.rest.issues.updateComment({ comment_id: comment.id, owner, repo, body })
                : github.rest.issues.createComment({ issue_number, owner, repo, body });
