name: Type Report
on:
  - pull_request
  - push

jobs:
  type_report:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Type Report
        run: npm run type:report > type-coverage.txt

      - name: Type Comment Finding
        if: ${{ github.event.action == 'synchronize' }}
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: type-coverage

      - name: Type Comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: ./type-coverage.txt
          edit-mode: replace
